name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
    -  '**.md'
    -  '.gitignore'
    -  'docker-compose.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
    -  '**.md'
    -  '.gitignore'
    -  'docker-compose.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build backend with Gradle
        run: ./gradlew clean :backend:build
        
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
        
      - name: Build frontend with npm
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
